% gaborInfo = getGaborData(folderName,tag,channelNum)
% This program reads the information about gabor atoms from the files
% generated by MP.

% Inputs
% folderName and tag: Standard inputs that specify the data
% channelNum: channel number of interest

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Supratim Ray, 2008 
% Distributed under the General Public License.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Updates
% 20/8/14: Minor changes to make the code work on all platforms
% 1/10/14: Minor name changes for some programs

function gaborInfo = getGaborData(folderName,tag,channelNum)

fn = platformSpecificNameMPP(fullfile(folderName,tag,['GaborMP/mp0.bok.' conv2Str(channelNum-1)]));
fd = fopen(fn,'r');

numAtoms=0;
trialNum=1;

while (~isempty(numAtoms))
    
    fread(fd,1,'int'); % nvars
    fread(fd,1,'int'); % window numb
    numAtoms=fread(fd,1,'int'); %no of atoms
    sigE=fread(fd,1,'double');
    sigE=sigE^2;
    
    if (~isempty(numAtoms))       
        gaborInfo{trialNum}.numAtoms    = numAtoms; %#ok<*AGROW>
        gaborInfo{trialNum}.sigE        = sigE;
        
        x=zeros(5,numAtoms);
        for i=1:numAtoms
            clear k;
            k=fread(fd,4,'short');
            x(1:3,i)=k(2:4);
            x(4:5,i)=fread(fd,2,'double');
        end
        gaborInfo{trialNum}.gaborData = x;
        clear x;
        trialNum=trialNum+1;
    end
end

fclose(fd);
end